// HalluScribe - unit tests for the profile writer (profile.md, meta, digest).

use super::*;
use chrono::TimeZone;

fn tmp_dir(name: &str) -> PathBuf {
    let d = std::env::temp_dir().join(format!("halluscribe_profile_writer_{name}"));
    let _ = fs::remove_dir_all(&d);
    d
}

fn entry(id: &str, project: &str, session_type: &str, tags: Vec<&str>) -> IndexEntry {
    IndexEntry {
        id: id.to_string(),
        project: project.to_string(),
        date: "2026-06-01".to_string(),
        title: format!("Session {id}"),
        tool: "Claude Code".to_string(),
        fill_pct: 90.0,
        session_timestamp: "2026-06-01T00:00:00+00:00".to_string(),
        updated_at: String::new(),
        session_type: session_type.to_string(),
        error_tags: tags.into_iter().map(str::to_string).collect(),
        topic_tags: Vec::new(),
        archive_path: format!("sessions/{project}/{id}.md"),
        source_jsonl: String::new(),
        source_size_bytes: 0,
        provider: "claude_code".to_string(),
        fill_estimated: false,
        transcript_hash: String::new(),
    }
}

fn sample_sections() -> ProfileSections {
    ProfileSections {
        identity: "Rust/Tauri developer.".to_string(),
        projects: "HalluScribe [s1]".to_string(),
        conventions: String::new(),
        recurring_problems: String::new(),
        communication_style: String::new(),
        timeline: String::new(),
    }
}

#[test]
fn write_profile_contains_skeleton_and_all_sections() {
    let dir = tmp_dir("skeleton");
    let meta = ProfileMeta {
        generated_at: "2026-07-03T00:00:00+00:00".to_string(),
        last_distilled_ts: "2026-07-01T00:00:00+00:00".to_string(),
        session_count: 5,
        sources: vec!["claude_code".to_string()],
        facts_count: 3,
    };
    let path = write_profile(&dir, &sample_sections(), &meta).unwrap();
    let content = fs::read_to_string(&path).unwrap();
    assert!(content.starts_with(&format!(
        "# User Profile — generated by HalluScribe {HALLUSCRIBE_VERSION} on 2026-07-03 from 5 sessions"
    )));
    for section in ProfileSection::ALL {
        assert!(content.contains(&format!("## {}", section.heading())));
    }
    assert!(content.contains("Rust/Tauri developer."));
    assert!(content.contains("_No facts distilled yet._"));
}

#[test]
fn write_profile_writes_meta_roundtrip() {
    let dir = tmp_dir("meta_roundtrip");
    let meta = ProfileMeta {
        generated_at: "2026-07-03T00:00:00+00:00".to_string(),
        last_distilled_ts: "2026-07-01T00:00:00+00:00".to_string(),
        session_count: 5,
        sources: vec!["claude_code".to_string(), "codex".to_string()],
        facts_count: 3,
    };
    write_profile(&dir, &sample_sections(), &meta).unwrap();
    let loaded = load_meta(&dir);
    assert_eq!(loaded.session_count, 5);
    assert_eq!(loaded.facts_count, 3);
    assert_eq!(loaded.sources, meta.sources);
    assert_eq!(loaded.last_distilled_ts, "2026-07-01T00:00:00+00:00");
}

#[test]
fn load_meta_defaults_when_absent() {
    let dir = tmp_dir("meta_absent");
    let meta = load_meta(&dir);
    assert_eq!(meta.session_count, 0);
    assert!(meta.last_distilled_ts.is_empty());
}

#[test]
fn read_profile_md_none_when_absent() {
    let dir = tmp_dir("profile_absent");
    assert!(read_profile_md(&dir).is_none());
}

#[test]
fn read_profile_md_some_after_write() {
    let dir = tmp_dir("profile_present");
    let meta = ProfileMeta {
        generated_at: "2026-07-03T00:00:00+00:00".to_string(),
        ..Default::default()
    };
    write_profile(&dir, &sample_sections(), &meta).unwrap();
    let content = read_profile_md(&dir).unwrap();
    assert!(content.contains("Rust/Tauri developer."));
}

#[test]
fn digest_filename_uses_iso_week() {
    let dir = tmp_dir("digest_filename");
    // 2026-07-06 is a Monday; ISO week 28 of 2026.
    let now = Utc.with_ymd_and_hms(2026, 7, 6, 12, 0, 0).unwrap();
    let entries = [entry("s1", "proj", "building", vec!["exit code 127"])];
    let refs: Vec<&IndexEntry> = entries.iter().collect();
    let path = write_digest(&dir, &refs, &[], now).unwrap();
    assert_eq!(
        path.file_name().unwrap().to_str().unwrap(),
        "digest-2026-W28.md"
    );
}

#[test]
fn digest_content_has_counts_and_facts() {
    let dir = tmp_dir("digest_content");
    let now = Utc.with_ymd_and_hms(2026, 7, 6, 12, 0, 0).unwrap();
    let entries = [
        entry("s1", "proj-a", "building", vec!["exit code 127"]),
        entry("s2", "proj-a", "debugging", vec!["exit code 127"]),
        entry("s3", "proj-b", "building", vec![]),
    ];
    let refs: Vec<&IndexEntry> = entries.iter().collect();
    let facts = vec![ProfileFact {
        section: ProfileSection::Timeline,
        fact: "Started HalluScribe.".to_string(),
        evidence: vec!["s1".to_string()],
        date: "2026-06-01".to_string(),
    }];
    let path = write_digest(&dir, &refs, &facts, now).unwrap();
    let content = fs::read_to_string(&path).unwrap();
    assert!(content.contains("3 sessions distilled this refresh."));
    assert!(content.contains("proj-a: 2"));
    assert!(content.contains("proj-b: 1"));
    assert!(content.contains("building: 2"));
    assert!(content.contains("debugging: 1"));
    assert!(content.contains("exit code 127: 2"));
    assert!(content.contains("Started HalluScribe."));
}

#[test]
fn digest_content_handles_no_facts_and_no_errors() {
    let dir = tmp_dir("digest_empty");
    let now = Utc.with_ymd_and_hms(2026, 7, 6, 12, 0, 0).unwrap();
    let entries = [entry("s1", "proj", "exploration", vec![])];
    let refs: Vec<&IndexEntry> = entries.iter().collect();
    let path = write_digest(&dir, &refs, &[], now).unwrap();
    let content = fs::read_to_string(&path).unwrap();
    assert!(content.contains("_None._"));
}

#[test]
fn latest_digest_none_when_absent() {
    let dir = tmp_dir("digest_none");
    assert!(latest_digest(&dir).is_none());
}

#[test]
fn latest_digest_picks_newest_week() {
    let dir = tmp_dir("digest_latest");
    let profile = dir.join("profile");
    fs::create_dir_all(&profile).unwrap();
    fs::write(profile.join("digest-2026-W27.md"), "older week").unwrap();
    fs::write(profile.join("digest-2026-W28.md"), "newer week").unwrap();
    assert_eq!(latest_digest(&dir).unwrap(), "newer week");
}

#[test]
fn incremental_watermark_advances_to_newest_selected_session() {
    // Simulates the mod.rs orchestration picking selected.first() (newest,
    // since select_sources sorts newest-first) as the new watermark.
    let selected = [
        entry("newer", "proj", "building", vec![]),
        entry("older", "proj", "building", vec![]),
    ];
    let refs: Vec<&IndexEntry> = selected.iter().collect();
    let newest = refs.first().unwrap().session_timestamp.clone();
    assert_eq!(newest, "2026-06-01T00:00:00+00:00");
}
