// HalluScribe - deterministic assembly: profile.md + profile_meta.json from
// merged sections, and the weekly digest from the map step's raw facts. No
// inference happens here - this module only formats and writes.

use super::types::{ProfileFact, ProfileMeta, ProfileSection, ProfileSections};
use super::ProfileError;
use crate::archive::IndexEntry;
use chrono::{DateTime, Datelike, Utc};
use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};

const HALLUSCRIBE_VERSION: &str = env!("CARGO_PKG_VERSION");

fn profile_dir(archive_dir: &Path) -> PathBuf {
    archive_dir.join("profile")
}

pub fn load_meta(archive_dir: &Path) -> ProfileMeta {
    let path = profile_dir(archive_dir).join("profile_meta.json");
    fs::read_to_string(path)
        .ok()
        .and_then(|raw| serde_json::from_str(&raw).ok())
        .unwrap_or_default()
}

pub fn read_profile_md(archive_dir: &Path) -> Option<String> {
    fs::read_to_string(profile_dir(archive_dir).join("profile.md")).ok()
}

/// Content of the newest `digest-*.md`, or `None` when no digest exists yet.
/// `digest-<year>-W<week>.md` names sort chronologically as plain strings, so
/// the lexicographic maximum is the latest week.
pub fn latest_digest(archive_dir: &Path) -> Option<String> {
    let dir = profile_dir(archive_dir);
    let newest = fs::read_dir(&dir)
        .ok()?
        .filter_map(|entry| entry.ok())
        .map(|entry| entry.file_name().to_string_lossy().into_owned())
        .filter(|name| name.starts_with("digest-") && name.ends_with(".md"))
        .max()?;
    fs::read_to_string(dir.join(newest)).ok()
}

/// Write profile.md and profile_meta.json.
pub fn write_profile(
    archive_dir: &Path,
    sections: &ProfileSections,
    meta: &ProfileMeta,
) -> Result<PathBuf, ProfileError> {
    let dir = profile_dir(archive_dir);
    fs::create_dir_all(&dir)?;

    let date = meta.generated_at.get(..10).unwrap_or(&meta.generated_at);
    let markdown = build_profile_markdown(date, meta.session_count, sections);
    let profile_path = dir.join("profile.md");
    fs::write(&profile_path, markdown)?;
    fs::write(
        dir.join("profile_meta.json"),
        serde_json::to_string_pretty(meta)?,
    )?;

    Ok(profile_path)
}

fn build_profile_markdown(date: &str, session_count: usize, sections: &ProfileSections) -> String {
    let mut out = format!(
        "# User Profile — generated by HalluScribe {HALLUSCRIBE_VERSION} on {date} from {session_count} sessions\n\n"
    );
    for section in ProfileSection::ALL {
        out.push_str(&format!("## {}\n\n", section.heading()));
        let body = sections.get(section);
        let body = if body.is_empty() {
            "_No facts distilled yet._"
        } else {
            body
        };
        out.push_str(body);
        out.push_str("\n\n");
    }
    out
}

/// Write `digest-<ISO-week>.md`: a deterministic (no-inference) rollup of the
/// sessions this refresh mapped, plus the new facts' one-liners.
pub fn write_digest(
    archive_dir: &Path,
    selected: &[&IndexEntry],
    facts: &[ProfileFact],
    now: DateTime<Utc>,
) -> Result<PathBuf, ProfileError> {
    let dir = profile_dir(archive_dir);
    fs::create_dir_all(&dir)?;

    let iso_week = now.iso_week();
    let filename = format!("digest-{}-W{:02}.md", iso_week.year(), iso_week.week());
    let path = dir.join(filename);
    fs::write(&path, build_digest_markdown(selected, facts))?;
    Ok(path)
}

fn build_digest_markdown(selected: &[&IndexEntry], facts: &[ProfileFact]) -> String {
    let mut by_project: HashMap<&str, u32> = HashMap::new();
    let mut by_type: HashMap<&str, u32> = HashMap::new();
    let mut error_counts: HashMap<&str, u32> = HashMap::new();
    for entry in selected {
        *by_project.entry(entry.project.as_str()).or_insert(0) += 1;
        *by_type.entry(entry.session_type.as_str()).or_insert(0) += 1;
        for tag in &entry.error_tags {
            *error_counts.entry(tag.as_str()).or_insert(0) += 1;
        }
    }

    let mut out = format!(
        "# Weekly Digest\n\n{} sessions distilled this refresh.\n\n",
        selected.len()
    );

    out.push_str("## By project\n\n");
    for (project, count) in sorted_desc(&by_project) {
        out.push_str(&format!("- {project}: {count}\n"));
    }

    out.push_str("\n## By type\n\n");
    for (session_type, count) in sorted_desc(&by_type) {
        out.push_str(&format!("- {session_type}: {count}\n"));
    }

    out.push_str("\n## Top new error tags\n\n");
    let top_errors = sorted_desc(&error_counts);
    if top_errors.is_empty() {
        out.push_str("_None._\n");
    } else {
        for (tag, count) in top_errors.into_iter().take(10) {
            out.push_str(&format!("- {tag}: {count}\n"));
        }
    }

    out.push_str("\n## New facts\n\n");
    if facts.is_empty() {
        out.push_str("_None._\n");
    } else {
        for f in facts {
            out.push_str(&format!(
                "- [{}] {} [{}]\n",
                f.date,
                f.fact,
                f.evidence.join(", ")
            ));
        }
    }

    out
}

fn sorted_desc<'a>(counts: &HashMap<&'a str, u32>) -> Vec<(&'a str, u32)> {
    let mut pairs: Vec<(&str, u32)> = counts.iter().map(|(k, v)| (*k, *v)).collect();
    pairs.sort_by(|a, b| b.1.cmp(&a.1).then_with(|| a.0.cmp(b.0)));
    pairs
}

#[cfg(test)]
#[path = "writer_tests.rs"]
mod tests;
